# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LockApp
    pod 'Toast-Swift', '~> 5.0.0'
    pod 'MBProgressHUD'
    pod 'UIColor_Hex_Swift',:inhibit_warnings => false
    pod 'CarbonKit'
    pod 'IQKeyboardManagerSwift'
    pod 'RealmSwift'
    pod 'Gallery'
    pod 'BiometricAuthentication'
    pod 'Hue'
    pod 'Imaginary', '~> 3.0.3'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SwiftyJSON'
    pod 'KRProgressHUD'
    pod 'SwiftyStoreKit'
    pod 'PromiseKit'
    pod 'Toast-Swift'
    pod 'Kingfisher'
    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'Firebase/Core'


end
